server:
  port: 9999

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/tfs?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
mybatis:
  configuration:
    map-underscore-to-camel-case: true
logging:
      level:
        com.yaorange.tqt.mapper: debug
up:
  imageRoot: E:\nginx-1.16.1\html\images\
  musicRoot: E:\nginx-1.16.1\html\music\
  prefixImage: http://localhost/images/
  prefixMusic: http://localhost/music/